<?php defined("ABSPATH") || die("!");
function gov_language(){
	return [
		//general
		"comment_label" => "Komentar",
		"recommended_series" => "Series Terkait",
		"wpb_get_post_views_label" => "{{count}} Views",
		"view_all_label" => "View All",
		"previous" => "Previous",
		"next" => "Next",
		"surprise_me_label" => "Surprise Me!",
		"ago" => "lalu",
		//home 
		"home_hot_series_update_label" => "Terpopuler Hari Ini",
		"home_project_release_label" => "Project Update",
		"home_blog_release_label" => "Blog",
		"home_latest_release_label" => "Rilisan Terbaru",
		"mini_ch" => "Ch. ",
		//home slider
		"home_slider_trending_label" => "{{blogname}} <b>Trending</b> Minggu Ini",
		"home_slider_summary_label" => "Summary",
		"home_recommended" => "Rekomendasi",
		//bookmark
		"bookmark_head" => "Anda dapat menyimpan daftar anime di sini hingga {{max}} judul. Daftar ditampilkan berdasarkan tanggal update terbaru. Daftar anime disimpan di browser yang anda gunakan saat ini.",
		"bookmark_no_item" => "YOU HAVE NO BOOKMARK, NOTHING TO SHOW",
		"delete" =>  "Hapus",

		//chapter single page 
		"chapter_to_chapter_list_link" => 'Semua chapter ada di <a href="{{link}}">{{text}}</a>',
		"chapter_before_readerarea_text" => 'Baca manga <b>{{chapter_title}}</b> bahasa Indonesia terbaru di <b>{{blogname}}</b>. Manga <b>{{manga_title}}</b> bahasa Indonesia selalu update di <b>{{blogname}}</b>. Jangan lupa membaca update manga lainnya ya. Daftar koleksi manga <b>{{blogname}}</b> ada di menu Daftar Manga.',
		//chapter single page dropdown chapter selection
		"chapter_drop_down_select_chapter_label" => "Pilih Chapter",

		"chapter_download_label" => "Download",
		"chapter_nav_previous_label" => "Prev",
		"chapter_nav_next_label" => "Next",
		"chapter_after_readerarea_tags" => 'baca manga {{chapter_title}} bahasa Indonesia, komik {{chapter_title}} bahasa Indonesia, baca {{chapter_title}} online, {{chapter_title}} bab, {{chapter_title}} chapter, {{chapter_title}} high quality, {{chapter_title}} manga scan',
		"chapter_after_readerarea_novel_tags" => 'baca novel {{chapter_title}} bahasa Indonesia, novel {{chapter_title}}, baca {{chapter_title}} online, {{chapter_title}} chapter, {{chapter_title}} high quality, {{chapter_title}} light novel',
		//chapter single page, reader area 
		"chapter_readerarea_no_images" => '<h2>BELUM ADA CHAPTER</h2>',
		"chapter_readerarea_default_server_label" => "Server 1",

		//series single page
		"series_info_alt_label" => "Alternative",
		"series_info_synopsis_label" => 'Sinopsis {{post_title}}',
		"series_info_genres_label" => "Genres",
		"series_info_author_label" => "Author",
		"series_info_artist_label" => "Artist",
		"series_info_posted_on_label" => "Posted On",
		"series_info_status_label" => "Status",
		"series_info_released_label" => "Released",
		"series_info_type_label" => "Type",
		"series_info_posted_by_label" => "Posted By",
		"series_info_updated_on_label" => "Updated On",
		"series_info_serialization_label" => "Serialization",
		"series_info_rating_label" => "Rating {{rating}}",
		"series_bottom_keyword_text" => '<strong>Keywords: </strong> <a href="{{link}}">baca {{post_title}}</a>, <a href="{{link}}">{{post_title}} bahasa Indonesia</a>, <a href="{{link}}">{{post_title}} sub indo</a>, <a href="{{link}}">download {{post_title}} sub indo</a>',
		"series_bookmarked_by" => "Followed by {{count}} people",
		"series_keywords_text" => "baca {{manga_title}}, {{manga_title}} indonesia, {{manga_title}} indo, download {{manga_title}} indo, baca {{manga_title}} online",
		"series_nsfw" => "Peringatan, series berjudul \"{{manga_title}}\" di dalamnya mungkin terdapat konten kekerasan, berdarah, atau seksual yang tidak sesuai dengan pembaca di bawah umur.",
		"series_gallery_label" => "Galeri {{manga_title}}",
		"series_chapter_list" => "Chapter {{manga_title}}",
		"series_read_button_label" => "Baca",
		"widget_chapter_label" => "Chapter",
		"search_chapter_placeholder" => "Cari Chapter. Contoh: 25 atau 178",
		"series_chapter_number" => "Chapter",
		"series_chapter_date" => "Date",
		"series_chapter_download" => "Download",
		"series_first_chapter_label" => "Chapter Awal",
		"series_new_chapter_label" => "Chapter Baru",
		"series_chapter_search_no_result" => "Chapter Tidak Ditemukan",

		//blog 
		"blog_meta" => "Diposting oleh {{author}} pada {{time}}",

		//advanced search series
		"filter_all_label" => "All",
		"filter_default_label" => "Default",
		"advanced_search_manga_list_label" => "Manga Lists",
		"advanced_search_filter_button_label" => "Filter",
		"advanced_search_series_title_label" => "Title",
		"advanced_search_series_year_label" => "Year",
		"advanced_search_series_status_label" => "Status",
		"advanced_search_series_status_all_label" => "All",
		"advanced_search_series_status_ongoing_label" => "Ongoing",
		"advanced_search_series_status_completed_label" => "Completed",
		"advanced_search_series_type_label" => "Type",
		"advanced_search_series_type_all_label" => "All",
		"advanced_search_series_order_by_label" => "Order by",
		"advanced_search_series_order_by_az_label" => "A-Z",
		"advanced_search_series_order_by_za_label" => "Z-A",
		"advanced_search_series_order_by_latest_update_label" => "Update",
		"advanced_search_series_order_by_latest_added_label" => "Added",
		"advanced_search_series_order_by_popular_label" => "Popular",
		"advanced_search_series_genre_label" => "Genre",
		"advanced_search_series_show_genre_label" => "Show Genre",
		"advanced_search_series_text_mode_label" => "Text Mode",
		"advanced_search_series_image_mode_label" => "Image Mode",
		"advanced_search_series_search_button_label" => "Cari",
		
		//widget
		"widget_popular_weekly" => "Mingguan",
		"widget_popular_monthly" => "Bulanan",
		"widget_popular_alltime" => "Semua",

		//footer 
		"footer_az_heading" => "A-Z LIST",
		"footer_az_text" => "Cari manga dari A sampai Z.",
		"footer_disclaimer" => "Semua komik di website ini hanya preview dari komik aslinya, mungkin terdapat banyak kesalahan bahasa, nama tokoh, dan alur cerita. Untuk versi aslinya, silahkan beli komiknya jika tersedia di kotamu.",
		
		"search_page_title" => "Cari '{{title}}'",
		"search_page_notfound" => "Tidak Ditemukan",
		"search_placeholder" => "Cari",
		"series_info_keywords_label" => "Keywords: ",
		"select_chapter_label" => "Chapter",
		"home_genre_label" => "All Manga",
		"thumbnail_color_label" => "Warna",
		"darkmode_label" => "Dark?",
		"related_blog_label" => "Rekomendasi",
		"reading_mode_full_label" => "Full Page",
		"reading_mode_single_label" => "Single Page",
		"reading_nav_next_label" => "Next",
		"reading_nav_prev_label" => "Prev",
		"readerarea_tags_label" => "Tags:",
		"thumbnail_novel_label" => "Novel",
		"seriestu_first_chapter_label" => "Awal:",
		"seriestu_new_chapter_label" => "Terbaru:",

		//2.2.1
		"warning_enter_label" => "Enter",
		"warning_exit_label" => "Exit",
		"widget_genre_title_view_label" => "Lihat semua series dari genre",
		"series_info_additional_label" => "Konten Tambahan",
		'series_history_title' => "Terakhir Anda Baca",
		'series_history_prefixAgo' => "",
		'series_history_prefixFromNow' => "",
		'series_history_suffixAgo' => "lalu",
		'series_history_suffixFromNow' => "dari sekarang",
		'series_history_seconds' => "kurang dari semenit",
		'series_history_minute' => "sekitar satu menit",
		'series_history_minutes' => "{{num}} menit",
		'series_history_hour' => "sekitar sejam",
		'series_history_hours' => "sekitar {{num}} jam",
		'series_history_day' => "sehari",
		'series_history_days' => "{{num}} hari",
		'series_history_month' => "sekitar sebulan",
		'series_history_months' => "{{num}} bulan",
		'series_history_year' => "sekitar setahun",
		'series_history_years' => "{{num}} tahun",

		//2.1.2
		'bookmark_disabled' => "FITUR BOOKMARK TIDAK DIAKTIF",
	];
};